config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users,
    controllers: { registrations: "registrations" }
  devise_scope :user do
    post "create_demo_user", to: "registrations#add_demo_user"
  end
  root to: "pages#home"
  get "/dashboard", to: "dashboard#show"
  post "add_discovery", to: "dashboard#add_discovery_method"
  get "mentions_legales", to: "pages#mentions_legales"
  # ############### MOBILE ROUTES###############
  namespace "mobile" do
    resources :work_plans, only: [:index]
    resources :students, only: [:results]
    resources :classrooms, only: [:index, :show] do
      resources :students, only: [:show, :index]
    end
    get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  end
  # ############### CONTACTROUTES ###############
  post "", to: "contact#create", as: :contact_create
  post "contacts/user_request", to: "contact#user_request", as: :user_request
  get "contacts/new", to: "contact#new", as: :new_contact
  get "contacts/demo_request", to: "contact#demo_request", as: :demo_request

  # ############### WORK_PLAN ROUTES###############
  resources :work_plans, only: [:index, :show, :update, :new, :create, :destroy] do
    resources :work_plan_domains, only: [:new, :create]
    post "", to: "work_plans#clone", as: :clone
  end
  get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  # post "work_plans/:id", to: "work_plans#share", as: :share

  resources :work_plan_domains, only: [:destroy, :show] do
    resources :work_plan_skills, only: [:create]
  end
  # ############### routes for RESULTS###############
  resources :results, only: [:destroy,:create] do
    member do
      patch :validate
    end

  end
  #
  # ############### END routes for RESULTS###############

  # ############### routes for WORK_PLAN_SKILLS###############
  resources :work_plan_skills, only: [:update, :destroy, :show] do
    member do
      patch :move
    end
    resources :challenges, only: [:create, :update]
    post "/challenges/:id", to: "challenges#clone", as: :clone
    get "remove_special_wps", to: "work_plan_skills#remove_special_wps", as: :remove_special_wps
    patch "eval_update", to: "work_plan_skills#eval_update", as: :eval_update
    # completed / failed / redo
    patch "change_challenge", to: "work_plan_skills#change_challenge", as: :change_challenge
    post "challenges/:id/display_challenges", to: "challenges#display_challenges", as: :display_challenges
  end

  # ###############routes for CLASSROOMS###############
  resources :classrooms, only: [:index, :show, :update, :new, :create, :destroy] do
    member do
      get :results_by_domain
      get :results
      post :generate_pdfs
    end
    resources :students, only: [:new, :edit] # :create, :destroy
    resources :shared_classrooms, only: [:create, :destroy]
  end
  # get "classrooms/:id/results_by_domain", to: "classrooms#results_by_domain", as: :results_by_domain
  # get "classrooms/:id/results", to: "classrooms#results", as: :classroom_results
  # get "classrooms/:id/generate_pdfs", to: "classrooms#generate_pdfs", as: :generate_pdfs

  # ###############routes for STUDENTS###############
  resources :students, only: [:create, :update, :show, :destroy] do
    get "domains/:id/modal", to: "modals#display_skills_modal", as: :display_skills_modal
    resources :belts, only: [:create]
    post "", to: "work_plans#auto_new_wp", as: :auto_new_wp
    get "domains/:id/:level", to: "belts#show", as: :show
    get "new_validated_wps", to: "students#new_validated_wps", as: :new_validated_wps
    post "new_validated_wps", to: "work_plan_skills#add_validated_wps", as: :add_validated_wps
    get "add_completed_wps", to: "students#add_completed_wps", as: :add_completed_wps
  end

  # ###############routes for BELTS###############
  resources :belts, only: [:destroy, :edit, :update]

  # ###############route for tab editing###############
  resources :tables, only: [:show, :create, :update]

  # ###############stripe routes###############
  # namespace :stripe do
  #   mount StripeEvent::Engine, at: "/stripe-webhooks"
  # end
  get "create-customer-portal-session", to: "stripe/stripe#create_portal_session"
  # get "/session-status", to: "stripe/checkouts#session_status"
  post "stripe-webhooks", to: "stripe/stripe_webhooks#create"
  # get "subscription-checkout", to: "stripe/checkouts#subscription_checkout"
  # ###############END OF STRIPE ROUTES ############

  # ############### Subscriptions ###############
  get "subscriptions/on_boarding", to: "subscriptions#on_boarding"
  resources :subscriptions, only: [:create, :new]
  get "subscriptions/success", to: "subscriptions#success"
  get "subscriptions/cancel", to: "subscriptions#cancel"
  get "subscriptions/school_pricing", to: "subscriptions#school_pricing"
  # ###############END OF Subscriptions ROUTES############

  # ###############routes for SKILLS###############
  get "skills/add_skills_from_xls", to: "skills#add_skills_from_xls", as: :add_skills_from_xls
  resources :skills do
    member do
      patch :move
    end
  end
  # EXCEL UPLAD SKILLS
  # get "excel/upload", to: "excel#upload", as: "upload_excel"
  post "skills/upload", to: "skills#upload_skills_xlsx", as: :upload_skills
  # ###############END for SKILLS###############

  # ###############routesfor Challenge#########
  resources :challenges, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # ###############routes for SCHOOL/SCHOOL_ROLES###############
  get "schools/join", to: "schools#join", as: :join_school
  post "schools/create_sub_with_code", to: "school_roles#create"
  resources :schools, only: %w[show new create]

  # ###############    routes for GRADES /DOMAINS        ###############
  resources :grades, only: [:show, :destroy, :index, :new, :create] do
    resources :domains, only: [:new, :index]
  end
  # ###############    routes for DOMAINS         ###############
  resources :domains, only: [:show, :edit, :update, :create, :destroy] do
    member do
      patch :move
    end
  end
  # ###############ROUTES FOR MODALS###############
  get "students/:id/auto_gen", to: "modals#auto_gen", as: :student_auto_gen_modal

  # ###############END for SKILLS###############

  # ###############ROUTES FOR CONVERSATIONS###############
  resources :conversations, only: [:index, :create, :show, :edit, :update] do
    member do
      post "add_user"
      delete "remove_user"
    end
    collection do
      post "contact_user"
    end
    resources :messages, only: [:create]
  end

  # ###############END for CONVERSATIONS###############
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_conversations, dependent: :destroy
  has_many :users, through: :user_conversations

  validates :conversation_type, presence: true, inclusion: { in: %w[ensemble group school classic] }
  validate :unique_ensemble_conversation_per_user, if: -> { conversation_type == "ensemble" }
  scope :classic, -> { where(conversation_type: "classic") }
  scope :school, -> { where(conversation_type: "school") }
  scope :ensemble, -> { includes(:users).where(conversation_type: "ensemble") }

  # get conversation for the ensemble user
  def is_group?
    conversation_type == "group"
  end

  def is_school?
    conversation_type == "school"
  end

  def is_classic?
    conversation_type == "classic"
  end

  def is_ensemble?
    conversation_type == "ensemble"
  end

  def add_user!(user)
    users << user
    self.conversation_type = "group" if users.count > 1
    save
  end

  def unread_messages_for_user?(user)
    messages.any? { |message| !user.have_read?(message) }
  end

  def mark_as_read!(user)
    messages.each { |message| message.mark_as_read! for: user }
  end

  def self.find_or_create_ensemble(user)
    conversation = includes(messages: [:user, :rich_text_content])
      .where(conversation_type: "ensemble")
      .joins(:users).find_by(users: { id: user.id })
    unless conversation
      conversation = create(conversation_type: "ensemble", name: "Ensemble & #{user.first_name}")
      conversation.users << user
    end
    conversation
  end

  # get conversion for the school user
  def self.find_or_create_school_conversation(user)
    # Trouver ou créer la conversation de type "school" pour l'école de l'utilisateur
    school = user.school
    conversation = Conversation.includes([:users, { messages: [:user, :rich_text_content] }])
      .where(conversation_type: "school")
      .joins(users: :school_role)
      .find_by(school_roles: { school_id: school.id })
    unless conversation
      conversation = Conversation.create(conversation_type: "school", name: school.name)
      UserConversation.create(user: user, conversation: conversation)
    end
    conversation
  end

  def self.find_or_create_classic_conversation(user, contact)
    conversation = user.conversations.classic.joins(:users).find_by(users: { id: contact.id })
    unless conversation
      conversation = Conversation.create!(conversation_type: "classic", name: "#{contact.first_name} & #{user.first_name}")
      UserConversation.create(user: user, conversation: conversation)
      UserConversation.create(user: contact, conversation: conversation)
    end
    conversation
  end

  private

  def unique_ensemble_conversation_per_user
    users.each do |user|
      if user.conversations.ensemble.exists?
        errors.add(:base, "A user can only have one 'ensemble' conversation.")
        break
      end
    end
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation, only: [:show, :edit, :update, :destroy, :add_user, :remove_user]
  before_action :set_index_conversations, only: [:index]
  # after_action :verify_authorized, except: :index

  def index
    skip_policy_scope
    # @user = User.includes([:avatar_attachment]).find(current_user.id)
    if params[:conversation_id].present?
      @conversation = Conversation.includes(messages: [:user, :rich_text_content]).find(params[:conversation_id])
      @collegue_not_in_conversation = @collegues_with_avatars.reject { |collegue| @conversation.users.include?(collegue) }
      @conversation.mark_as_read!(current_user)
    else
      @conversation = @school_conversation || @school_conversations.sort_by(&:id).first
      @conversation.mark_as_read!(current_user)
    end
  end

  def contact_user
    @contact = User.find(params[:contact_id])
    # la creation d'un conversation doit se faire avec comme paramas le conversation_type ()
    skip_authorization
    @conversation = Conversation.find_or_create_classic_conversation(current_user, @contact)
    @collegue_not_in_conversation = current_user.collegues_with_avatars.reject { |collegue| @conversation.users.include?(collegue) }
    respond_to do |format|
      format.html { redirect_to conversations_path(conversation_id: @conversation.id) }
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("conversation", partial: "conversations/conversation",
                                                                  locals: { conversation: @conversation, collegue_not_in_conversation: @collegue_not_in_conversation })
      }
    end
  end

  def show
    @collegue_not_in_conversation = current_user.collegues_with_avatars.reject { |collegue| @conversation.users.include?(collegue) }
  end

  def add_user
    @new_user = User.find(params[:new_user_id])
    @conversation.add_user!(@new_user)
    @collegue_not_in_conversation = current_user.collegues_with_avatars.reject { |collegue| @conversation.users.include?(collegue) }
    respond_to do |format|
      format.html { redirect_to conversations_path(conversation_id: @conversation.id) }
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("conversation", partial: "conversations/conversation",
                                                                  locals: { conversation: @conversation, collegue_not_in_conversation: @collegue_not_in_conversation })
      }
    end
  end

  def remove_user
    Rails.logger.info("###################### \n Remove user #{current_user.id} from
    conversation #{@conversation.id}\n######################")
    @conversation.users.delete(current_user)
    @conversation.update(conversation_type: "classic") if @conversation.users.count == 1
    redirect_to conversations_path
  end

  def edit
  end

  def update
    @conversation.update(update_params)
    respond_to do |format|
      format.html { redirect_to conversations_path(conversation: @conversation.id) }
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("conversation_#{@conversation.id}_name",
                                                  partial: "conversations/name",
                                                  locals: { conversation: @conversation })
      }
    end
  end

  private

  def set_conversation
    @conversation = Conversation.find(params[:id])
    authorize @conversation
  end

  def update_params
    params.require(:conversation).permit(:name)
  end

  def set_index_conversations
    if current_user.admin?
      @school_conversations = Conversation.includes(messages: [:user, :rich_text_content]).where(conversation_type: "school")
    else
      @school_conversation = Conversation.find_or_create_school_conversation(current_user)
    end
    @ensemble_conversation = Conversation.find_or_create_ensemble(current_user) unless current_user.admin?
    @user_conversations = current_user.classic_and_group_conversations
    @collegues_with_avatars = current_user.collegues_with_avatars
    @ensemble_conversations = Conversation.ensemble if current_user.admin?
  end

  def conversation_params
    params.require(:conversation).permit(:conversation_type, :user_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= turbo_frame_tag "conversation", class:"conversation", data:{conversation_target: "conversation"} do %>
	<div class="conversation-header">
		<%= render "conversations/name", conversation: conversation %>
		<div class="conversation-users">
			<% conversation.users.shuffle.each do |user| %>
				<%  if (!user.admin? && !conversation.is_ensemble?) %>
					<div class="conversation-user"
          data-controller="tooltip"
          data-bs-toggle="tooltip"
          data-bs-placement="top"
          title="<%=user.first_name%>">
						<%= image_tag user.avatar_url, class:"avatar-basic"%>
					</div>
				<% end %>
			<% end %>
			<div class="" data-controller='toggle-panel'>
				<% if !collegue_not_in_conversation.nil? && ((conversation.is_group?) || (conversation.is_classic?))%>
					<h2 class='m-0 ms-1'  data-toggle-panel-target="btn" data-action="click->toggle-panel#displayPanel">
						<i class="fa-solid fa-user-plus --roseL --cursor-pointer"></i>
					</h2>
					<div class="collegue-list d-none ms-1" data-toggle-panel-target="panel" data-action="click->toggle-panel#displayPanel">
						<% collegue_not_in_conversation.each do |user| %>
							<%= link_to add_user_conversation_path(conversation, new_user_id: user.id), method: :post, data:{turbo_frame: "conversation"} do%>
								<div class="collegue"
                  data-controller="tooltip"
                  data-bs-toggle="tooltip"
                  data-bs-placement="left"
                  title="<%=user.first_name%>">
									<%= image_tag user.avatar_url, class:"avatar-basic" %>
								</div>
							<% end %>
						<% end %>
						<div class="toogle-up avatar-basic mt-2">
							<i class="fa-solid fa-chevron-up fa-lg --roseL --cursor-pointer"></i>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<%= turbo_stream_from "conversation_#{conversation.id}_messages" %>
	<%= turbo_frame_tag "messages", class:"messages", data:{conversation_target: "messages"} do %>
		<% conversation.messages.sort_by(&:created_at).each do |message| %>
			<%= render 'messages/message', message: message, user: current_user %>
		<% end %>
	<% end %>
	<%= simple_form_for [conversation,Message.new],
      html: {novalidate: false,
      data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }} do |f| %>
		<div class="new-message-form">
			<%= f.input :content,as: :rich_text_area,input_html: {style:"min-height: 100% !important;"},
          required: true, label: false %>
			<%= button_tag :submit do%>
				<i class="fas fa-paper-plane"></i>
			<% end %>
		</div>
	<% end %>
<% end %>

app/views/conversations/_conversations.html.erb
<div class="conversations-list" data-controller="conversation-list">
	<%= render 'conversations/school_conversations', active_conversation:,
  school_conversation: , school_conversations: %>
	<% unless current_user.admin? %>
		<%= render 'conversations/ensemble_conversation',ensemble_conversation:,active_conversation: %>
	<% end %>
	<% if user_conversations%>
		<% user_conversations.each do |conversation| %>
			<%= link_to conversation_path(conversation),data:{turbo_frame: "conversation"} do%>
				<div class="conversation-link <%='active' if conversation == active_conversation%>"
              data-conversation-list-target="conversation"
              data-action="click->conversation-list#addActive">
					<div class="d-flex">
						<%if conversation.unread_messages_for_user?(current_user)%>
							<i class="fa-solid fa-circle bullet-chat-2" data-conversation-list-target="bullet"></i>
						<% end %>
						<div class="header" data-controller="tooltip"
                  data-bs-toggle="tooltip"
                  data-bs-placement="left"
                  title="<%=conversation.name%>">
							<% if conversation.is_group? %>
								<div class="avatar-basic">
									<i class="fa-solid fa-comments" style="font-size: x-large;"></i>
								</div>
							<% else %>
								<% user = conversation.users.where.not(id: current_user.id) %>
								<% if user %>
									<%= image_tag user.first.avatar_url, class: "avatar-basic",width: "40px" %>
								<% else %>
									<%= image_tag current_user.avatar_url, class: "avatar-basic",width: "40px" %>
								<% end %>
							<% end %>
						</div>
					</div>
					<%= render 'messages/last_message', message: conversation.messages.last, conversation: %>
				</div>
			<% end %>
		<% end %>
	<% end %>
	<% if current_user.admin? %>
		<%= render "conversations/ensemble_conversations",active_conversation: active_conversation , ensemble_conversations: @ensemble_conversations if @ensemble_conversations%>
	<% end %>
	<div class="contact-collegue">
		<%= button_tag  class: "btn-flat-no-hover" do %>
			Contacter <i class="fa-solid fa-comment"></i>
		<% end %>
		<%= render 'conversations/create_conversation', collegues_with_avatars: @collegues_with_avatars, collegue_not_in_conversation: @collegue_not_in_conversation %>
	</div>
</div>

app/views/conversations/_create_conversation.html.erb
  <div class="user-avatars">
    <% collegues_with_avatars.each do |user| %>
      <%= link_to contact_user_conversations_path(contact_id: user.id), class: 'avatar-link',
      data: {turbo_frame_tag: "_top",
          user_id: user.id,
          controller:"tooltip",
          bs_toggle:"tooltip",
          bs_placement:"top",
          method: :post},
          title: user.first_name do %>
        <%= image_tag user.avatar_url, alt: user.first_name, class: 'avatar-basic' %>
      <% end %>
    <% end %>
  </div>

app/views/conversations/_ensemble_conversation.html.erb
<%= link_to  conversation_path(ensemble_conversation),data:{turbo_frame: "conversation"} do%>
	<div class="conversation-link <%='active' if ensemble_conversation == active_conversation%>"
      data-conversation-list-target="conversation"
      data-action="click->conversation-list#addActive">
		<div class="d-flex">
			<%if ensemble_conversation.unread_messages_for_user?(current_user)%>
				<i class="fa-solid fa-circle bullet-chat-2" data-conversation-list-target="bullet"></i>
			<% end %>
			<div class="header" data-controller="tooltip"
          data-bs-toggle="tooltip"
          data-bs-placement="left"
          title="Ensemble">
				<%= image_tag 'icons/apple-icon.png', width: "40px" %>
			</div>
		</div>
		<%= render 'messages/last_message', message: ensemble_conversation.messages.last, conversation: ensemble_conversation %>
	</div>
<%end%>

app/views/conversations/_ensemble_conversations.html.erb
<h3>ADMIN ENSEMBLE</h3>
<% ensemble_conversations.each do |ensemble_conversation| %>
	<%if ensemble_conversation.unread_messages_for_user?(current_user) && !ensemble_conversation.users.where.not(id: current_user.id).empty?%>
		<%= link_to  conversation_path(ensemble_conversation),data:{turbo_frame: "conversation"} do%>
			<div class="conversation-link <%='active' if ensemble_conversation == active_conversation%>"
      data-conversation-list-target="conversation"
      data-action="click->conversation-list#addActive">
				<div class="d-flex">
					<%if ensemble_conversation.unread_messages_for_user?(current_user)%>
						<i class="fa-solid fa-circle bullet-chat-2" data-conversation-list-target="bullet"></i>
					<% end %>
					<% teacher = ensemble_conversation.users.where.not(id: current_user.id).first  %>
					<div class="header" data-controller="tooltip"
          data-bs-toggle="tooltip"
          data-bs-placement="left"
          title="<%= teacher.school.name + " " + teacher.first_name%>">
						<%= image_tag teacher.avatar_url, class: "avatar-basic",width: "40px" %>
					</div>
				</div>
				<%= render 'messages/last_message', message: ensemble_conversation.messages.last, conversation: ensemble_conversation %>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/conversations/_name.html.erb
<%= turbo_frame_tag "conversation_#{@conversation.id}_name" do %>
	<div class="conversation-title">
		<%= conversation.name %>
		<% if conversation.conversation_type == "group" || conversation.conversation_type == "classic" %>
			<%= link_to edit_conversation_path(conversation) do%>
				<i style= 'color: #F24150' class="fas fa-pen fa-xs ms-2" ></i>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/conversations/_school_conversations.html.erb
<%# for non-admin users  %>
<% if current_user.admin? %>
  <% unless school_conversations.nil? %>
    <% school_conversations.sort_by(&:id).each do |school_conversation| %>
      <%= link_to conversation_path(school_conversation),data:{turbo_frame: "conversation"} do%>
        <div class="conversation-link <%='active' if school_conversation == active_conversation%> "
        data-conversation-list-target="conversation"
        data-action="click->conversation-list#addActive">
          <%if school_conversation.unread_messages_for_user?(current_user)%>
            <i class="fa-solid fa-circle bullet-chat-2" data-conversation-list-target="bullet"></i>
          <% end %>
          <div class="header" data-controller="tooltip"
              data-bs-toggle="tooltip"
              data-bs-placement="left"
              title="<%= school_conversation.users.first.school.name %>"            >
            <i class="fa-solid fa-school --rose" style="font-size: x-large;">
            </i>
          </div>
          <%= render 'messages/last_message', message: school_conversation.messages.last, conversation: school_conversation %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <% unless school_conversation.nil? %>
    <%= link_to conversation_path(school_conversation),data:{turbo_frame: "conversation"} do%>
      <div class="conversation-link <%='active' if school_conversation == active_conversation%> "
        data-conversation-list-target="conversation"
        data-action="click->conversation-list#addActive">
        <%if school_conversation.unread_messages_for_user?(current_user)%>
          <i class="fa-solid fa-circle bullet-chat-2" data-conversation-list-target="bullet"></i>
        <% end %>
        <div class="header" data-controller="tooltip"
              data-bs-toggle="tooltip"
              data-bs-placement="left"
              title="<%= current_user.school.name %>"            >
          <i class="fa-solid fa-school --rose" style="font-size: x-large;">
          </i>
        </div>
        <%= render 'messages/last_message', message: school_conversation.messages.last, conversation: school_conversation %>
      </div>
    <% end %>
  <% end %>
<% end %>

<%# for admin users  %>

app/views/conversations/edit.html.erb
<%= turbo_frame_tag "conversation_#{@conversation.id}_name" do %>
	<div class="conversation-title">
		<%= simple_form_for @conversation,html: { novalidate: false } do |f|%>
			<div class="d-flex">
				<%= f.input :name, label: false, input_html:{class:"--border-10px"}, required: true %>
				<%= button_tag type: 'submit', class: '--bgc-transparent', style:"padding: 5px;" do %>
					<i class="fa-solid fa-circle-check text-success" style="font-size: 26px;"></i>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/conversations/index.html.erb
<div class="d-flex">
	<h1 class='ms-5'>Conversations</h1>
	<h6 class='--roseL'>BETA</h6>
</div>
<div class="conversations-container">
	<%= render 'conversations/conversations', school_conversation: @school_conversation,
              school_conversations: @school_conversations,
              active_conversation: @conversation, ensemble_conversation: @ensemble_conversation,
              user_conversations: @user_conversations %>
	<%# conversation = @school_conversation # Only for front dev%>
	<% unless is_mobile_device? %>
		<%= render 'conversations/conversation', conversation: @conversation,
  collegue_not_in_conversation: @collegue_not_in_conversation %>
	<% end %>
</div>

app/views/conversations/show.html.erb
<%= render 'conversations/conversation', conversation: @conversation, collegue_not_in_conversation: @collegue_not_in_conversation %>