config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users,
    controllers: { registrations: "registrations" }
  devise_scope :user do
    post "create_demo_user", to: "registrations#add_demo_user"
  end
  root to: "pages#home"
  get "/dashboard", to: "dashboard#show"
  post "add_discovery", to: "dashboard#add_discovery_method"
  get "mentions_legales", to: "pages#mentions_legales"
  # ############### MOBILE ROUTES###############
  namespace "mobile" do
    resources :work_plans, only: [:index]
    resources :students, only: [:results]
    resources :classrooms, only: [:index, :show] do
      resources :students, only: [:show, :index]
    end
    get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  end
  # ############### CONTACTROUTES ###############
  post "", to: "contact#create", as: :contact_create
  post "contacts/user_request", to: "contact#user_request", as: :user_request
  get "contacts/new", to: "contact#new", as: :new_contact
  get "contacts/demo_request", to: "contact#demo_request", as: :demo_request

  # ############### WORK_PLAN ROUTES###############
  resources :work_plans, only: [:index, :show, :update, :new, :create, :destroy] do
    resources :work_plan_domains, only: [:new, :create]
    post "", to: "work_plans#clone", as: :clone
  end
  get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  # post "work_plans/:id", to: "work_plans#share", as: :share

  resources :work_plan_domains, only: [:destroy, :show] do
    resources :work_plan_skills, only: [:create]
  end
  # ############### routes for RESULTS###############
  resources :results, only: [:destroy,:create] do
    member do
      patch :validate
    end

  end
  #
  # ############### END routes for RESULTS###############

  # ############### routes for WORK_PLAN_SKILLS###############
  resources :work_plan_skills, only: [:update, :destroy, :show] do
    member do
      patch :move
    end
    resources :challenges, only: [:create, :update]
    post "/challenges/:id", to: "challenges#clone", as: :clone
    get "remove_special_wps", to: "work_plan_skills#remove_special_wps", as: :remove_special_wps
    patch "eval_update", to: "work_plan_skills#eval_update", as: :eval_update
    # completed / failed / redo
    patch "change_challenge", to: "work_plan_skills#change_challenge", as: :change_challenge
    post "challenges/:id/display_challenges", to: "challenges#display_challenges", as: :display_challenges
  end

  # ###############routes for CLASSROOMS###############
  resources :classrooms, only: [:index, :show, :update, :new, :create, :destroy] do
    member do
      get :results_by_domain
      get :results
      post :generate_pdfs
    end
    resources :students, only: [:new, :edit] # :create, :destroy
    resources :shared_classrooms, only: [:create, :destroy]
  end
  # get "classrooms/:id/results_by_domain", to: "classrooms#results_by_domain", as: :results_by_domain
  # get "classrooms/:id/results", to: "classrooms#results", as: :classroom_results
  # get "classrooms/:id/generate_pdfs", to: "classrooms#generate_pdfs", as: :generate_pdfs

  # ###############routes for STUDENTS###############
  resources :students, only: [:create, :update, :show, :destroy] do
    get "domains/:id/modal", to: "modals#display_skills_modal", as: :display_skills_modal
    resources :belts, only: [:create]
    post "", to: "work_plans#auto_new_wp", as: :auto_new_wp
    get "domains/:id/:level", to: "belts#show", as: :show
    get "new_validated_wps", to: "students#new_validated_wps", as: :new_validated_wps
    post "new_validated_wps", to: "work_plan_skills#add_validated_wps", as: :add_validated_wps
    get "add_completed_wps", to: "students#add_completed_wps", as: :add_completed_wps
  end

  # ###############routes for BELTS###############
  resources :belts, only: [:destroy, :edit, :update]

  # ###############route for tab editing###############
  resources :tables, only: [:show, :create, :update]

  # ###############stripe routes###############
  # namespace :stripe do
  #   mount StripeEvent::Engine, at: "/stripe-webhooks"
  # end
  get "create-customer-portal-session", to: "stripe/stripe#create_portal_session"
  # get "/session-status", to: "stripe/checkouts#session_status"
  post "stripe-webhooks", to: "stripe/stripe_webhooks#create"
  # get "subscription-checkout", to: "stripe/checkouts#subscription_checkout"
  # ###############END OF STRIPE ROUTES ############

  # ############### Subscriptions ###############
  get "subscriptions/on_boarding", to: "subscriptions#on_boarding"
  resources :subscriptions, only: [:create, :new]
  get "subscriptions/success", to: "subscriptions#success"
  get "subscriptions/cancel", to: "subscriptions#cancel"
  get "subscriptions/school_pricing", to: "subscriptions#school_pricing"
  # ###############END OF Subscriptions ROUTES############

  # ###############routes for SKILLS###############
  get "skills/add_skills_from_xls", to: "skills#add_skills_from_xls", as: :add_skills_from_xls
  resources :skills do
    member do
      patch :move
    end
  end
  # EXCEL UPLAD SKILLS
  # get "excel/upload", to: "excel#upload", as: "upload_excel"
  post "skills/upload", to: "skills#upload_skills_xlsx", as: :upload_skills
  # ###############END for SKILLS###############

  # ###############routesfor Challenge#########
  resources :challenges, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # ###############routes for SCHOOL/SCHOOL_ROLES###############
  get "schools/join", to: "schools#join", as: :join_school
  post "schools/create_sub_with_code", to: "school_roles#create"
  resources :schools, only: %w[show new create]

  # ###############    routes for GRADES /DOMAINS        ###############
  resources :grades, only: [:show, :destroy, :index, :new, :create] do
    resources :domains, only: [:new, :index]
  end
  # ###############    routes for DOMAINS         ###############
  resources :domains, only: [:show, :edit, :update, :create, :destroy] do
    member do
      patch :move
    end
  end
  # ###############ROUTES FOR MODALS###############
  get "students/:id/auto_gen", to: "modals#auto_gen", as: :student_auto_gen_modal

  # ###############END for SKILLS###############

  # ###############ROUTES FOR CONVERSATIONS###############
  resources :conversations, only: [:index, :create, :show, :edit, :update] do
    member do
      post "add_user"
      delete "remove_user"
    end
    collection do
      post "contact_user"
    end
    resources :messages, only: [:create]
  end

  # ###############END for CONVERSATIONS###############
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/work_plan.rb
# frozen_string_literal: true

class WorkPlan < ApplicationRecord
  belongs_to :user
  belongs_to :grade #to remove for first migration Of Grade MODEL
  belongs_to :shared_user, class_name: "User", optional: true
  belongs_to :student, optional: true

  has_many :work_plan_domains, dependent: :destroy
  accepts_nested_attributes_for :work_plan_domains

  has_many :work_plan_skills, through: :work_plan_domains
  accepts_nested_attributes_for :work_plan_skills
  has_many :challenges, through: :work_plan_skills
  has_many :skills, through: :work_plan_skills

  validates :name, presence: true

  def all_domains_from_work_plan
    WorkPlanDomain::DOMAINS[grade.grade_level]
  end

  def special_wps?
    special_wps == true
  end

  def self.with_associations
    includes( [:skills, :challenges] )
  end
end

app/controllers/mobile/work_plans_controller.rb
class Mobile::WorkPlansController < ApplicationController
  layout 'mobile'
  def index
    # @my_classrooms = Classroom.where(user: current_user)
    # @my_work_plans = WorkPlan.where(user: current_user).order(created_at: :DESC) # .sort_by(&:student)
    # @my_work_plans_unassigned = @my_work_plans.where(student: nil)
    # @my_work_plans = @my_work_plans.where.not(student: nil).sort_by(&:student)
    @shared_classrooms = current_user.shared_classrooms
    shared_classrooms = @shared_classrooms.map(&:classroom)
    @my_classrooms = (current_user.classrooms + shared_classrooms).sort_by(&:created_at)
    shared_work_plans = []
    shared_classrooms.each do |classroom|
      classroom.students.each do |shared_student|
        WorkPlan.where(student: shared_student, special_wps: false).order(created_at: :DESC).each do |work_plan|
          shared_work_plans << work_plan
        end
      end
    end
    @my_work_plans = policy_scope(WorkPlan)
    # .sort_by(&:student)
    @my_work_plans_unassigned = @my_work_plans.where(student: nil)
    @my_work_plans = @my_work_plans.where.not(student: nil).sort_by(&:student)
    @my_work_plans += shared_work_plans
  end

  def evaluation
    # @belt = Belt::BELT_COLORS
    @work_plan = WorkPlan.find(params[:id])
    authorize @work_plan
    @domains = @work_plan.grade.domains.sort_by(&:position)
    @previous = []
    @student =@work_plan.student
    @wpds = @work_plan.work_plan_domains
    @wpds.each do |wpd|
      wpd.work_plan_skills.each do |wps|
        # last_4_wps = WorkPlanSkill.where(student: @work_plan.student, skill: wps.skill_id).sort_by(&:created_at).reverse[1..3]
        last_4_wps = WorkPlanSkill.last_4_wps(@work_plan, wps, @work_plan.student)
        @previous << [wps.skill_id, last_4_wps]
      end
    end
  end
end

app/views/work_plans/_domain.html.erb
<div class='domain  ' id="<%= dom_id(work_plan_domain) %>">
	<%# DOMAIN + BELT DISPLAY %>
	<div class='p-1 d-flex'>
		<div class='domain-belt-level'>
			<div class='domain-display d-flex justify-content-start'>
				<%# Button remove Domain %>
				<%= link_to work_plan_domain_path(work_plan_domain), method: :delete, data: { confirm: "Voulez vous enlever ce domaine?" } do %>
					<div class='rmv-skill-btn mt-3 me-2'>
						<i class="far fa-times-circle"></i>
					</div>
				<% end %>
				<%= work_plan_domain.domain%></div>
			<div >
				<div class='d-flex justify-content-around belt-display '>
					<div class='bd-maison' >
						<i class=" fas fa-bacon belt-<%= work_plan_domain.level %> display-2 font-weight-bold"></i>
					</div>
				</div>
				<div class='d-flex justify-content-around mt-1 belt-display' <%  if (@work_plan.grade != "CM2" && ['Géométrie', 'Grandeurs et Mesures'].include?(work_plan_domain.domain)) then%> style = 'visibility: hidden'<%end%> >
					<strong><%= Belt::BELT_COLORS[work_plan_domain.level-1].capitalize%></strong>
				</div>
			</div>
		</div>
		<%# SKILLS DISPLAY  %>
		<div class='p-2 skill-display'>
			<% work_plan_domain.work_plan_skills.order(:skill_id).each do |plan_skill| %>
				<%= render 'show_skill_display', plan_skill: plan_skill%>
			<% end %>
			<%# add skill on domain %>
			<div data-controller="skill-add" class='pt-3'>
				<div data-skill-add-target="button" data-action="click->skill-add#displayForm" class='add-skill-btn'>
					<h6>Ajouter une compétence  </h6>
					<i class="fas fa-chevron-right"></i>
				</div>
				<div class="d-none" data-skill-add-target="form">
					<%= simple_form_for [WorkPlanSkill.new ], html: { novalidate: false }, url:  work_plan_domain_work_plan_skills_path(work_plan_domain), method: :post, class:'d-flex'  do |f| %>
						<div class=" d-flex justify-content-between pb-1 ">
							<div class='d-flex '>
								<%= select_tag :skill, options_from_collection_for_select(Skill.where(domain: work_plan_domain.domain ,level: work_plan_domain.level, grade: @work_plan.grade, school: current_user.school).order(:symbol,:id), :id,:name), :prompt => "Sélectionnez Une compétences",class: 'skill-selector', :required => true %>
							</div>
							<div>
								<%= select_tag :kind, raw("<option>jeu</option><option>exercice</option><option>ceinture</option>"), :prompt => "Sélectionnez Un type" ,class: 'skill-selector', :required => true %>
							</div>
						</div>
						<div class='d-flex'>
							<%= f.submit 'Valider' ,class: 'add-skill-btn' %>
							<div class="cancel-btn ms-3" data-action="click->skill-add#displayForm" style='margin-top: 10px'>
								<i class="fas fa-times"></i>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<%# show 1 exo %>
	<%# <div > %>
	<% work_plan_domain.work_plan_skills.order(:skill_id).each do |work_plan_skill| %>
		<% if (work_plan_skill.kind == 'exercice') %>
			<%# <div data-controller='ajax-replace-challenge' data-ajax-replace-challenge-target="challengeDisplay" id="<%=work_plan_skill.id%>
			<%= render 'work_plan_skills/work_plan_skill_challenge', work_plan_skill: work_plan_skill%>
			<%# </div> %>
		<% end %>
	<% end %>
	<%# </div> %>
</div>

app/views/work_plans/_eval_work_plan_domains.html.erb
<%# work_plan.work_plan_domains.each do |work_plan_domain|%>
	<%# <%raise%>
	<%@domains.each do |domain|%>
		<% wpd2 = @wpds.select {|wpd|wpd.domain ==domain}%>
		<% unless wpd2.empty? %>
			<%wpd2.sort_by{ |wpd|wpd.level }.each do |work_plan_domain|%>
				<%# boucle sur les work_plan_domains %>
				<div class='domain-block'>
					<%= render 'eval_domain', work_plan_domain: work_plan_domain%>
				</div>
			<%end%>
		<% end %>
	<% end %>

app/views/work_plans/_header_wp.html.erb
<div data-controller='edit-wpheader'>
  <div class='' data-edit-wpheader-target="button">
    <div class='d-flex justify-content-between align-items-baseline' >
      <h1><%= work_plan.name%><i style= 'color: #F24150' class="fas fa-pen fa-xs ml-2" data-action="click->edit-wpheader#displayForm"></i></h1>
      <p>Niveau : <%= work_plan.grade%></p>
      <center>
        <h4 class='date-domain'>Du <%= work_plan.start_date.strftime("%d/%m/%Y")%> Au <%= work_plan.end_date.strftime("%d/%m/%Y")%></h4>
      </center>
    </div>
  </div>
  <%# edit div for WP header %>
  <div class='edit-wp d-none' data-edit-wpheader-target="form">
    <%= simple_form_for work_plan, class: 'd-flex justify-content-between align-items-baseline' do |f|%>
      <p class='m-left'>Nom :</p>
      <%= f.input :name, label: false,
                      placeholder: 'Nom :',
                      input_html: { class: 'area  m-left' } %>
      <div class=" d-flex">
        <p class='m-left'>Du</p>
        <div class='edit-cal_wp'>
          <%= f.input :start_date, as: :string, label: false,
                          input_html: {class: 'datepicker area m-left ', locale: "fr"} %>
        </div>
        <p class='m-left'>Au</p>
        <div class='edit-cal_wp mr-2'>
          <%= f.input :end_date, as: :string, label: false,
                          input_html: {class: 'datepicker area m-left', locale: "fr"} %>
        </div>
      </div>
      <p class='m-left'>Elève :</p>
      <%= f.association :student, label: false,
                            collection: current_user.students.order(:first_name),
                            input_html: {class: 'area grow m-left'},
                            label_method: :first_name %>
      <%= f.submit "Valider", class: 'area rect-sm btn-valid' %>
    <% end %>
  </div>
</div>

app/views/work_plans/_index_student_index.html.erb
<%= turbo_frame_tag student do %>
  <div data-controller='wp-by-student'>
    <%# START of folder + student name + student wp count %>
    <%= render "index_wp_student_name", student: student %>
    <%# END of folder + student name + student wp count %>
    <div
      data-wp-by-student-target="wplist"
      class='list-wp-index d-none'
      id=<%=student.id%>
    >
      <%= turbo_frame_tag "student_#{student.id}_work_plans" do %>
        <% my_work_plans.select { |a| a.student_id == student.id }.each do |wp| %>
          <%= turbo_frame_tag wp do %>
            <%= render "index_wp_line", wp: wp %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/work_plans/_index_wp_line.html.erb
<div class="index-wp-line" data-wp-by-student-target='wpLine'>
  <div class="eval_link">
    <%= link_to evaluation_path(wp), data:{turbo_frame: "work_plan_index"} do %>
      <i class="fa-solid fa-graduation-cap"></i>
    <% end %>
  </div>
  <div class="student-wp">
    <%= link_to work_plan_path(wp), target: '_blank' do %>
      <div class="namept">
        <%= wp.name %>
      </div>
      <div class="index-wp-count">
        <%= wp.grade.name %>
      </div>
      <div class="wp-dates">
        <%= wp.start_date.nil? ? "" : l(wp.start_date, format: "%d/%m/%Y") %>
        <%= wp.end_date.nil? ? "" : l(wp.end_date, format: "au %a. %d/%m/%Y") %>
      </div>
    <% end %>
  </div>
  <div class='rmv-wp'>
    <%= button_to work_plan_path(wp), method: :delete,
                                    class: '--bgc-blanc',
                                    data: {
                                      # action: "click->wp-by-student#deleteWorkPlan",
                                      confirm: "Voulez vous Supprimer Ce Plan de Travail?",
                                    } do %>
      <div class='rmv-skill-btn '>
        <i class="far fa-times-circle"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/work_plans/_index_wp_student_name.html.erb
<div class='d-flex wp-student-folder' data-action="click->wp-by-student#displayList">
  <div class="index-folder">
      <i class="fa-solid fa-folder-closed me-4 ms-3" data-wp-by-student-target="folderopen"
        ></i>
      <i class="fa-solid fa-folder-open me-4 ms-3 d-none" data-wp-by-student-target="folderclosed"
        ></i>
  </div>
  <div class='index-wp-name d-flex'>
    <div class="wp-firstname">
      <%= student.first_name%>
    </div>
  <div class='invisible'>
  --
  </div>
  <div class="index-wp-count" data-wp-by-student-target='count'>
  <%= turbo_frame_tag "student_#{student.id}_work_plan_count" do %>
    ( <%= @my_work_plans.select { |a| a.student_id == student.id }.count %> Plan<%= "s" if @my_work_plans.select { |a| a.student_id == student.id }.count > 1 %> de travail )
  <% end %>
    </div>
  </div>
</div>

app/views/work_plans/_shared_header_wp.html.erb
<div id="wp-edition" >
  <div >
    <div class='d-flex justify-content-between align-items-baseline' >
      <h1><%= work_plan.name%>
        <!-- EDIT WP Button trigger modal -->
        <button type="button" class="bg-white" data-bs-toggle="modal" data-bs-target="#exampleModal" >
          <i style= 'color: #F24150' class="fas fa-pen fa-xs ms-2" ></i>
        </button>
        <!-- END EDIT WP Button trigger modal -->
      </h1>
      <p>Niveau : <%= work_plan.grade.name%></p>
      <center>
        <h4 class='date-domain'>Du <%= work_plan.start_date.strftime("%d/%m/%Y")%> Au <%= work_plan.end_date.strftime("%d/%m/%Y")%></h4>
      </center>
    </div>
  </div>

</div>

app/views/work_plans/_show_cloning_panel.html.erb
<div class="cloning-form d-none" data-cloning-wp-target="cloningpanel">
	<div class= "btn-close-cloning-panel" data-action="click->cloning-wp#displayCloningForm">
		<i class="far fa-times-circle"></i>
	</div>
	<div class="simple-cloning d-flex d-flex justify-content-around align-items-center">
		<h1 >
			<%=@work_plan.name.capitalize%>
		</h1>
		<h4> Niveau: <%=@work_plan.grade.name.capitalize%></h4>
	</div>
	<div class="grey-line"></div>
	<div class="multiple-cloning">
		<h2>Clonage  et  Assignation</h2>
		<div class="class-list">
			<%= simple_form_for work_plan_clone_path(@work_plan) do |form|%>
				<% @classrooms_whithout_current_student.each do |classroom| %>
					<h3  class='ps-3'><%=classroom.grade.grade_level%>-<%=classroom.name%></h3>
					<div class="cloning-classroom-card" >
						<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
							<div class="student-checkbox" data-controller='checkboxes'>
								<%=form.input_field :students,
                # collection: classroom.students.order(first_name: :asc),
                collection:[Student.new(first_name: 'Tous',id: rand(-1000..0), classroom: classroom)]+classroom.students.reject{ |y| y == @work_plan.student }.sort_by{|e| e[:first_name]},
                label_method: :first_name,
                value_method: :id,
                multiple: true,
                as: :check_boxes,
                boolean_style: :inline,
                data: {checkboxes_target: 'boxes',action:"click->checkboxes#add"},
                class: "tag-selector",
                item_wrapper_class: 'tag-item'
                %>
							</div>
						</div>
					</div>
					<div class="grey-line"></div>
				<% end %>
				<div class='d-flex ps-3'>
					<%= form.submit 'Assigner aux élèves', class: 'btn-flat mt-3 mb-3 me-3', data: { confirm: "Etes vous bien sur de vouloir assigner ce plan de travail à tous les élèves sélectionnés" }%>
					<%= link_to work_plan_clone_path(@work_plan), method: "post", class: "btn-flat mt-3 mb-3 me-3  align-baseline" do %>
						<h6>Créer une copie sans élève assigné</h6>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/work_plans/_show_wp_sharing_modal.html.erb
<!-- Sharing Modal -->
<div class="modal fade" id="sharingModal" tabindex="-1" aria-labelledby="sharingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="sharingModalLabel">Partager avec </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for (work_plan), html: { novalidate: false }, method: "post" do |f|%>
        <div class="modal-body">
          <%=f.input :shared_user_id, label: false, required: true,
                              collection: teachers,
                              label_method: :first_name,
                              # value_method: :id,
                              input_html: {class: 'area add-teacher me-5'}
                                %>
        </div>
        <div class="modal-footer">
          <%= f.submit "partager", class: "utility-wp-btn",data:{bs_dismiss:"modal"} %>
          <%# <%= link_to work_plan_path(@work_plan,shared_to: current_user.id), class: "utility-wp-btn", method: "post" do %>
            <%# <h6>Partager</h6> %>
            <%# <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/work_plans/_skill_display.html.erb
                <div class='d-flex justify-content-between p-2 '>
                  <div class='border-skill justify-content-between mt-2'>
                    <div>
                      <%= plan_skill.skill.symbol%>
                      <%= plan_skill.skill.name%>
                    </div>
                    <%# Button remmove Skill %>
                    <div>
                      <%= link_to work_plan_skill_path(plan_skill), method: :delete, data: { confirm: "Voulez vous enlever cette compétence?" } do %>
                        <div class='rmv-skill-btn'>
                          <i class="far fa-times-circle"></i>
                        </div>
                      <% end %>
                    </div>
                    <%#  %>
                  </div>
                  <div class='challenge-kind '>
                    <%# les entete %>
                    <div class='d-flex justify-content-between w-100 kind-label'>
                      <div class='align-items-center'>J</div>
                      <div class='align-items-center'>E</div>
                      <div class='align-items-center'>C</div>
                    </div>
                    <%# les skills %>
                    <div class='d-flex justify-content-center w-100 kind-display'>
                      <div class='align-items-center cells'><% if plan_skill.kind.downcase == 'jeu' %>
                          <i class="fas fa-circle bullet-color"></i>
                        <% else %>
                          <i class="fas fa-circle text-white"></i>
                        <% end%>
                      </div>
                      <div class='align-items-center cells b-middle'>
                        <% if plan_skill.kind.downcase == 'exercice' %>
                          <i class="fas fa-circle bullet-color"></i>
                        <% else %>
                          <i class="fas fa-circle text-white"></i>
                        <% end%>
                      </div>
                      <div class='align-items-center cells'>
                        <% if (plan_skill.kind.downcase == 'controle') ||  (plan_skill.kind.downcase == 'ceinture')%>
                          <i class="fas fa-circle bullet-color"></i>
                        <% else %>
                          <i class="fas fa-circle text-white"></i>
                        <% end%>
                      </div>
                    </div>
                  </div >
                </div>

app/views/work_plans/destroy.turbo_stream.erb
<%= turbo_stream.remove @work_plan %>
<% if  @student.nil? %>
  <%= turbo_stream.update "unassigned_work_plan_count",
                      "#{@count} Plan#{"s" if @count > 1} de travail" %>
<% else %>
  <%= turbo_stream.update "student_#{@student.id}_work_plan_count",
                      "#{@count} Plan#{"s" if @count > 1} de travail" %>
<% end %>
<%= turbo_stream.prepend "flash" , partial: "shared/flashes" %>
 

app/views/work_plans/eval.html.erb
<div class=' pt ' data-controller='navigation loadingspinnermgnt'>
  <div class='eval-sticky-header' data-navigation-target='wp' >
    <div class="top-floating-btn" id='backToBottomBtn' data-action="click->navigation#backFunction">
      <i class="fa-solid fa-circle-arrow-down"></i>
    </div>
    <% # header WP %>
    <%= render "shared_header_wp", work_plan: @work_plan %>
    <% # Student details %>
    <div class='student-name d-flex justify-content-between'>
      <% unless @work_plan.student.nil? %>
        <%= link_to student_path(@work_plan.student),  class: 'student_name_link',data:{action: "click->loadingspinnermgnt#displaySpinner"} do%>
          <h2><strong><%= @work_plan.student.first_name %></strong></h2>
        <% end %>
      <% end %>
      <h1>Correction</h1>
      <%= link_to 'Retour Plan de travail', work_plan_path(@work_plan), class: 'utility-wp-btn eval-btn'%>
    </div>
  </div>
  <% # Start of a domain %>
  <div>
    <%= render "eval_work_plan_domains", work_plan: @work_plan %>
  </div>
  <div class="bottom-floating-btn" id='backToTopBtn' data-action="click->navigation#topFunction">
    <i class="fa-solid fa-circle-arrow-up"></i>
  </div>
</div>

app/views/work_plans/index.html.erb
<div class="container3" data-controller="display-right-anchor">
  <%= turbo_frame_tag "work_plan_index" do %>
    <% @my_classrooms.each do |classroom| %>
      <%= turbo_frame_tag classroom do %>
        <div class="wp-one-classroom">
          <h1>
            <%= "#{classroom.grade.grade_level.upcase} " %>
            <p class='ms-2'><%= classroom.name.nil? ? "" : "#{" - "} #{classroom.name}" %></p>
            <div class="sharing-details">
              <% if classroom.user != current_user %>
                <h6>Classe Partagée par
                  <%= classroom.user.first_name.capitalize %>
                </h6>
              <% end %>
            </div>
          </h1>
          <%# WP assigned %>
          <% classroom.students.order(:first_name).each do |student| %>
            <%= render "index_student_index", my_work_plans: @my_work_plans, student: student %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%# WP unassigned %>
    <% if @my_work_plans_unassigned.count > 0 %>
      <div data-controller="wplistunsigned" class=''>
        <%= render "index_unassigned_wp_list" %>
      </div>
    <% end %>
    <%# end classroom loop => class wp-one-classroom %>
  <% end %>
</div>