config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users,
    controllers: { registrations: "registrations" }
  devise_scope :user do
    post "create_demo_user", to: "registrations#add_demo_user"
  end
  root to: "pages#home"
  get "/dashboard", to: "dashboard#show"
  post "add_discovery", to: "dashboard#add_discovery_method"
  get "mentions_legales", to: "pages#mentions_legales"
  # ############### MOBILE ROUTES###############
  namespace "mobile" do
    resources :work_plans, only: [:index]
    resources :students, only: [:results]
    resources :classrooms, only: [:index, :show] do
      resources :students, only: [:show, :index]
    end
    get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  end
  # ############### CONTACTROUTES ###############
  post "", to: "contact#create", as: :contact_create
  post "contacts/user_request", to: "contact#user_request", as: :user_request
  get "contacts/new", to: "contact#new", as: :new_contact
  get "contacts/demo_request", to: "contact#demo_request", as: :demo_request

  # ############### WORK_PLAN ROUTES###############
  resources :work_plans, only: [:index, :show, :update, :new, :create, :destroy] do
    resources :work_plan_domains, only: [:new, :create]
    post "", to: "work_plans#clone", as: :clone
  end
  get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  # post "work_plans/:id", to: "work_plans#share", as: :share

  resources :work_plan_domains, only: [:destroy, :show] do
    resources :work_plan_skills, only: [:create]
  end
  # ############### routes for RESULTS###############
  resources :results, only: [:destroy,:create] do
    member do
      patch :validate
    end

  end
  #
  # ############### END routes for RESULTS###############

  # ############### routes for WORK_PLAN_SKILLS###############
  resources :work_plan_skills, only: [:update, :destroy, :show] do
    member do
      patch :move
    end
    resources :challenges, only: [:create, :update]
    post "/challenges/:id", to: "challenges#clone", as: :clone
    get "remove_special_wps", to: "work_plan_skills#remove_special_wps", as: :remove_special_wps
    patch "eval_update", to: "work_plan_skills#eval_update", as: :eval_update
    # completed / failed / redo
    patch "change_challenge", to: "work_plan_skills#change_challenge", as: :change_challenge
    post "challenges/:id/display_challenges", to: "challenges#display_challenges", as: :display_challenges
  end

  # ###############routes for CLASSROOMS###############
  resources :classrooms, only: [:index, :show, :update, :new, :create, :destroy] do
    member do
      get :results_by_domain
      get :results
      post :generate_pdfs
    end
    resources :students, only: [:new, :edit] # :create, :destroy
    resources :shared_classrooms, only: [:create, :destroy]
  end
  # get "classrooms/:id/results_by_domain", to: "classrooms#results_by_domain", as: :results_by_domain
  # get "classrooms/:id/results", to: "classrooms#results", as: :classroom_results
  # get "classrooms/:id/generate_pdfs", to: "classrooms#generate_pdfs", as: :generate_pdfs

  # ###############routes for STUDENTS###############
  resources :students, only: [:create, :update, :show, :destroy] do
    get "domains/:id/modal", to: "modals#display_skills_modal", as: :display_skills_modal
    resources :belts, only: [:create]
    post "", to: "work_plans#auto_new_wp", as: :auto_new_wp
    get "domains/:id/:level", to: "belts#show", as: :show
    get "new_validated_wps", to: "students#new_validated_wps", as: :new_validated_wps
    post "new_validated_wps", to: "work_plan_skills#add_validated_wps", as: :add_validated_wps
    get "add_completed_wps", to: "students#add_completed_wps", as: :add_completed_wps
  end

  # ###############routes for BELTS###############
  resources :belts, only: [:destroy, :edit, :update]

  # ###############route for tab editing###############
  resources :tables, only: [:show, :create, :update]

  # ###############stripe routes###############
  # namespace :stripe do
  #   mount StripeEvent::Engine, at: "/stripe-webhooks"
  # end
  get "create-customer-portal-session", to: "stripe/stripe#create_portal_session"
  # get "/session-status", to: "stripe/checkouts#session_status"
  post "stripe-webhooks", to: "stripe/stripe_webhooks#create"
  # get "subscription-checkout", to: "stripe/checkouts#subscription_checkout"
  # ###############END OF STRIPE ROUTES ############

  # ############### Subscriptions ###############
  get "subscriptions/on_boarding", to: "subscriptions#on_boarding"
  resources :subscriptions, only: [:create, :new]
  get "subscriptions/success", to: "subscriptions#success"
  get "subscriptions/cancel", to: "subscriptions#cancel"
  get "subscriptions/school_pricing", to: "subscriptions#school_pricing"
  # ###############END OF Subscriptions ROUTES############

  # ###############routes for SKILLS###############
  get "skills/add_skills_from_xls", to: "skills#add_skills_from_xls", as: :add_skills_from_xls
  resources :skills do
    member do
      patch :move
    end
  end
  # EXCEL UPLAD SKILLS
  # get "excel/upload", to: "excel#upload", as: "upload_excel"
  post "skills/upload", to: "skills#upload_skills_xlsx", as: :upload_skills
  # ###############END for SKILLS###############

  # ###############routesfor Challenge#########
  resources :challenges, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # ###############routes for SCHOOL/SCHOOL_ROLES###############
  get "schools/join", to: "schools#join", as: :join_school
  post "schools/create_sub_with_code", to: "school_roles#create"
  resources :schools, only: %w[show new create]

  # ###############    routes for GRADES /DOMAINS        ###############
  resources :grades, only: [:show, :destroy, :index, :new, :create] do
    resources :domains, only: [:new, :index]
  end
  # ###############    routes for DOMAINS         ###############
  resources :domains, only: [:show, :edit, :update, :create, :destroy] do
    member do
      patch :move
    end
  end
  # ###############ROUTES FOR MODALS###############
  get "students/:id/auto_gen", to: "modals#auto_gen", as: :student_auto_gen_modal

  # ###############END for SKILLS###############

  # ###############ROUTES FOR CONVERSATIONS###############
  resources :conversations, only: [:index, :create, :show, :edit, :update] do
    member do
      post "add_user"
      delete "remove_user"
    end
    collection do
      post "contact_user"
    end
    resources :messages, only: [:create]
  end

  # ###############END for CONVERSATIONS###############
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/domain.rb
class Domain < ApplicationRecord
  belongs_to :grade
  acts_as_list scope: :grade
  has_many :skills, dependent: :destroy
  has_many :belts, dependent: :destroy
  has_many :work_plan_domains, dependent: :destroy

  validates :name, presence: true,
                   uniqueness: { message: "Le nom de cet domain éxiste déja", scope: :grade }

  # METHODS
  delegate :grade_level, to: :grade

  def special?
    special == true
  end

  def all_skills_completed(student, level)
    skills_at_level = skills.select { |skill| skill.level == level }
    results = Result.completed.where(student:, skill: skills_at_level)
    skills_at_level.select do |skill|
      results.detect { |result| result.skill == skill && result.belt_validated? }
    end
  end

  def all_skills_completed?(student, level)
    # get all skills for a domain
    # temp_all_domain_skill = all_domain_skills
    skills_at_level = skills.select { |skill| skill.level == level }
    results = Result.completed.where(student:, skill: skills_at_level)
    skills_at_level.all? do |skill|
      results.find { |result| result.skill == skill && result.belt_validated? }
    end
  end
end

app/controllers/domains_controller.rb
# frozen_string_literal: true

class DomainsController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:index]
  before_action :set_domain, only: [:show,:edit, :destroy, :update, :move]

  def index
    @grade = Grade.find(params[:grade_id])
    @domains = @grade.domains
  end

  def new
    @grade = Grade.find(params[:grade_id])
    @domain = Domain.new(grade: @grade)

    authorize(@domain)
  end

  def show
    authorize(@domain)
  end

  def edit
    authorize(@domain)
    @grade = @domain.grade
  end

  def create
    @domain = Domain.new(set_params)
    @grade = @domain.grade
    authorize(@domain)
    @domain.save
    respond_to do |format|
      format.html { redirect_to grade_domains_path(@grade), notice: "Domaine Sauvegardé" }
      format.turbo_stream
    end
  end

  def update
    authorize @domain
    if @domain.update(set_params)
      respond_to do |format|
        format.html { redirect_to domain_path(@domain), notice: "Domaine Sauvegardé" }
        format.turbo_stream
      end
    else
      redirect_to redirect_to grade_domains_path(@domain.grade), notice: "Sauvegarde échouée "
    end
  end

  def destroy
    authorize @domain
    if @domain.destroy
      respond_to do |format|
        format.html { redirect_to grade_domains_path(@grade), notice: "Domaine Supprimé" }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to grade_domains_path(@grade), notice: "La suppression du domaine a échoué" }
        format.turbo_stream { render turbo_stream:
                                turbo_stream.replace(@domain,
                                  partial: "domains/domain",
                                  locals: { domain: @domain })
                            }
      end
    end
  end

  def move
    authorize @domain
    # binding.pry
    @domain.insert_at(params[:position].to_i)
  end

  private

  def set_domain
    @domain = Domain.find(params[:id])
  end

  def set_params
    params.require(:domain).permit(:grade_id, :name)
  end

  # def set_position
  #   params.require
  # end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_add_domain.html.erb
<%= turbo_frame_tag "new_domain" do%>
	<%= link_to  new_grade_domain_path(grade, Domain.new()) do%>
		<div class="domain-box form-domain-btn --bgc-rose --blanc ">
			Ajouter un domaine
		</div>
	<% end %>
<% end %>

app/views/domains/_domain.html.erb
<%=  turbo_frame_tag dom_id(domain), data:{id: domain.id} do%>
	<div class="domain-box" >
		<% if current_user.demo? %>
			<div class="--bgc-transparent p-0"
      data-controller="tooltip"
      data-bs-toggle="tooltip"
      data-bs-placement="top"
      title="Non disponible en Démo"
      >
				<i class="fas fa-pen fa-xs me-2" ></i>
			</div>
		<% else %>
			<%= link_to  edit_domain_path(domain) do%>
				<i class="fas fa-pen fa-xs me-2" ></i>
			<% end %>
		<% end %>
		<p class='grabbable'><%= domain.name %></p>
		<% if current_user.demo? %>
			<div class="--bgc-transparent p-0"
      data-controller="tooltip"
      data-bs-toggle="tooltip"
      data-bs-placement="right"
      title="Non disponible en Démo"
      >
				<i class="fa-solid fa-circle-xmark ms-2"></i>
			</div>
		<% else %>
			<%= button_to domain_path(domain), method: :delete,
            class: '--bgc-transparent p-0',
            data: {confirm: "Voulez-vous supprimer ce domaine ?
Vous supprimerez tous les exercices, compétences et évaluations liés à ce domaine."} do%>
				<i class="fa-solid fa-circle-xmark ms-2"></i>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/domains/_domains.html.erb
<div class="container3 mt-3">
	<h2 class='ms-5'>Gérer vos domaines pour le niveau <%= grade.name %></h2>
	<%= turbo_frame_tag "domains_index" do%>
		<%= turbo_frame_tag 'domains_list', data:{controller:'drag', drag_url_value:"/domains/:id/move"} do %>
			<% @domains.sort_by(&:position).each do |domain| %>
				<%= render 'domain', domain: domain %>
			<% end %>
		<% end %>
		<%= render 'domains/add_domain', grade: grade %>
	<% end %>
</div>

app/views/domains/_domains_list.html.erb
<div class="container3 mt-3">
	<h2 class='ms-5'>Gérer vos domaines pour le niveau <%= grade.name %></h2>
	<%= turbo_frame_tag "domains_index" do%>
		<%= turbo_frame_tag 'domains_list', data:{controller:'drag', drag_url_value:"/domains/:id/move"} do %>
			<% @domains.sort_by(&:position).each do |domain| %>
				<%= render 'one_domain', domain: domain %>
			<% end %>
		<% end %>
		<%= render 'domains/add_domain', grade: grade %>
	<% end %>
</div>

app/views/domains/_form.html.erb
<div class="domain-form-box form-domain-btn" >
	<%= simple_form_for [domain], html: { novalidate: false } do  |f| %>
		<div class="domain-form">
			<%= f.input :name, label: false,input_html:{maxlength:29}, required: true,class: '--bgc-transparent',
      placeholder: 'Nom du domaine' %>
			<div class="d-none">
				<%= f.association :grade, value:grade%>
			</div>
			<% if current_user.demo? %>
				<div class="--bgc-transparent m-1"
        data-controller="tooltip"
        data-bs-toggle="tooltip"
        data-bs-placement="top"
        title="Non disponible en Démo">
					<i class="fa-solid fa-circle-check"></i>
				</div>
			<% else %>
				<%= button_tag type: 'submit', class: '--bgc-transparent' do %>
					<i class="fa-solid fa-circle-check"></i>
				<% end %>
			<% end %>
			<% if domain.persisted? %>
				<%= link_to domain_path(domain),  class: '--bgc-transparent ' do %>
					<i class="fa-solid fa-circle-xmark --grisC"></i>
				<% end %>
			<% else%>
				<%= link_to grade_domains_path(grade),  class: '--bgc-transparent ' do %>
					<i class="fa-solid fa-circle-xmark --grisC"></i>
				<% end %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/domains/_one_domain.html.erb
<%=  turbo_frame_tag dom_id(domain), data:{id: domain.id} do%>
	<div class="domain-box" >
		<% if current_user.demo? %>
			<div class="--bgc-transparent p-0"
      data-controller="tooltip"
      data-bs-toggle="tooltip"
      data-bs-placement="top"
      title="Non disponible en Démo"
      >
				<i class="fas fa-pen fa-xs me-2" ></i>
			</div>
		<% else %>
			<%= link_to  edit_domain_path(domain) do%>
				<i class="fas fa-pen fa-xs me-2" ></i>
			<% end %>
		<% end %>
		<p class='grabbable'><%= domain.name %></p>
		<% if current_user.demo? %>
			<div class="--bgc-transparent p-0"
      data-controller="tooltip"
      data-bs-toggle="tooltip"
      data-bs-placement="right"
      title="Non disponible en Démo"
      >
				<i class="fa-solid fa-circle-xmark ms-2"></i>
			</div>
		<% else %>
			<%= button_to domain_path(domain), method: :delete,
            class: '--bgc-transparent p-0',
            data: {confirm: "Voulez-vous supprimer ce domaine ?
Vous supprimerez tous les exercices, compétences et évaluations liés à ce domaine."} do%>
				<i class="fa-solid fa-circle-xmark ms-2"></i>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/domains/create.turbo_stream.erb
<%= turbo_stream.append  "domains_list" do %>
  <%= render partial: "domain", locals: { domain: @domain } %>
<%end%>
<%= turbo_stream.replace "new_domain" do %>
  <%= render partial: "add_domain", locals: { grade: @grade } %>
<% end %>

app/views/domains/destroy.turbo_stream.erb
<%= turbo_stream.remove @domain %>

app/views/domains/edit.html.erb
<%= turbo_frame_tag @domain do %>
<%= render 'form', grade: @grade,domain: @domain %>
<% end %>

app/views/domains/index.html.erb
<p>Ecole <%= current_user.school.name %></p>
<%= turbo_frame_tag "skills_list" do%>
<%= render 'domains', grade: @grade, domain: @domain %>
<% end %>

app/views/domains/new.html.erb
<%= turbo_frame_tag "new_domain" do%>
<%= render 'form', grade:@grade, domain: @domain %>
<% end %>

app/views/domains/show.html.erb
<%= render 'domain', domain: @domain %>

app/views/domains/update.turbo_stream.erb
<%= turbo_stream.replace @domain do%>
  <%= render partial: "domain", locals: { domain: @domain } %>
<%end%>