config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users,
    controllers: { registrations: "registrations" }
  devise_scope :user do
    post "create_demo_user", to: "registrations#add_demo_user"
  end
  root to: "pages#home"
  get "/dashboard", to: "dashboard#show"
  post "add_discovery", to: "dashboard#add_discovery_method"
  get "mentions_legales", to: "pages#mentions_legales"
  # ############### MOBILE ROUTES###############
  namespace "mobile" do
    resources :work_plans, only: [:index]
    resources :students, only: [:results]
    resources :classrooms, only: [:index, :show] do
      resources :students, only: [:show, :index]
    end
    get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  end
  # ############### CONTACTROUTES ###############
  post "", to: "contact#create", as: :contact_create
  post "contacts/user_request", to: "contact#user_request", as: :user_request
  get "contacts/new", to: "contact#new", as: :new_contact
  get "contacts/demo_request", to: "contact#demo_request", as: :demo_request

  # ############### WORK_PLAN ROUTES###############
  resources :work_plans, only: [:index, :show, :update, :new, :create, :destroy] do
    resources :work_plan_domains, only: [:new, :create]
    post "", to: "work_plans#clone", as: :clone
  end
  get "work_plans/:id/evaluation", to: "work_plans#evaluation", as: :evaluation
  # post "work_plans/:id", to: "work_plans#share", as: :share

  resources :work_plan_domains, only: [:destroy, :show] do
    resources :work_plan_skills, only: [:create]
  end
  # ############### routes for RESULTS###############
  resources :results, only: [:destroy,:create] do
    member do
      patch :validate
    end

  end
  #
  # ############### END routes for RESULTS###############

  # ############### routes for WORK_PLAN_SKILLS###############
  resources :work_plan_skills, only: [:update, :destroy, :show] do
    member do
      patch :move
    end
    resources :challenges, only: [:create, :update]
    post "/challenges/:id", to: "challenges#clone", as: :clone
    get "remove_special_wps", to: "work_plan_skills#remove_special_wps", as: :remove_special_wps
    patch "eval_update", to: "work_plan_skills#eval_update", as: :eval_update
    # completed / failed / redo
    patch "change_challenge", to: "work_plan_skills#change_challenge", as: :change_challenge
    post "challenges/:id/display_challenges", to: "challenges#display_challenges", as: :display_challenges
  end

  # ###############routes for CLASSROOMS###############
  resources :classrooms, only: [:index, :show, :update, :new, :create, :destroy] do
    member do
      get :results_by_domain
      get :results
      post :generate_pdfs
    end
    resources :students, only: [:new, :edit] # :create, :destroy
    resources :shared_classrooms, only: [:create, :destroy]
  end
  # get "classrooms/:id/results_by_domain", to: "classrooms#results_by_domain", as: :results_by_domain
  # get "classrooms/:id/results", to: "classrooms#results", as: :classroom_results
  # get "classrooms/:id/generate_pdfs", to: "classrooms#generate_pdfs", as: :generate_pdfs

  # ###############routes for STUDENTS###############
  resources :students, only: [:create, :update, :show, :destroy] do
    get "domains/:id/modal", to: "modals#display_skills_modal", as: :display_skills_modal
    resources :belts, only: [:create]
    post "", to: "work_plans#auto_new_wp", as: :auto_new_wp
    get "domains/:id/:level", to: "belts#show", as: :show
    get "new_validated_wps", to: "students#new_validated_wps", as: :new_validated_wps
    post "new_validated_wps", to: "work_plan_skills#add_validated_wps", as: :add_validated_wps
    get "add_completed_wps", to: "students#add_completed_wps", as: :add_completed_wps
  end

  # ###############routes for BELTS###############
  resources :belts, only: [:destroy, :edit, :update]

  # ###############route for tab editing###############
  resources :tables, only: [:show, :create, :update]

  # ###############stripe routes###############
  # namespace :stripe do
  #   mount StripeEvent::Engine, at: "/stripe-webhooks"
  # end
  get "create-customer-portal-session", to: "stripe/stripe#create_portal_session"
  # get "/session-status", to: "stripe/checkouts#session_status"
  post "stripe-webhooks", to: "stripe/stripe_webhooks#create"
  # get "subscription-checkout", to: "stripe/checkouts#subscription_checkout"
  # ###############END OF STRIPE ROUTES ############

  # ############### Subscriptions ###############
  get "subscriptions/on_boarding", to: "subscriptions#on_boarding"
  resources :subscriptions, only: [:create, :new]
  get "subscriptions/success", to: "subscriptions#success"
  get "subscriptions/cancel", to: "subscriptions#cancel"
  get "subscriptions/school_pricing", to: "subscriptions#school_pricing"
  # ###############END OF Subscriptions ROUTES############

  # ###############routes for SKILLS###############
  get "skills/add_skills_from_xls", to: "skills#add_skills_from_xls", as: :add_skills_from_xls
  resources :skills do
    member do
      patch :move
    end
  end
  # EXCEL UPLAD SKILLS
  # get "excel/upload", to: "excel#upload", as: "upload_excel"
  post "skills/upload", to: "skills#upload_skills_xlsx", as: :upload_skills
  # ###############END for SKILLS###############

  # ###############routesfor Challenge#########
  resources :challenges, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # ###############routes for SCHOOL/SCHOOL_ROLES###############
  get "schools/join", to: "schools#join", as: :join_school
  post "schools/create_sub_with_code", to: "school_roles#create"
  resources :schools, only: %w[show new create]

  # ###############    routes for GRADES /DOMAINS        ###############
  resources :grades, only: [:show, :destroy, :index, :new, :create] do
    resources :domains, only: [:new, :index]
  end
  # ###############    routes for DOMAINS         ###############
  resources :domains, only: [:show, :edit, :update, :create, :destroy] do
    member do
      patch :move
    end
  end
  # ###############ROUTES FOR MODALS###############
  get "students/:id/auto_gen", to: "modals#auto_gen", as: :student_auto_gen_modal

  # ###############END for SKILLS###############

  # ###############ROUTES FOR CONVERSATIONS###############
  resources :conversations, only: [:index, :create, :show, :edit, :update] do
    member do
      post "add_user"
      delete "remove_user"
    end
    collection do
      post "contact_user"
    end
    resources :messages, only: [:create]
  end

  # ###############END for CONVERSATIONS###############
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :school

  enum status: {
    trialing: "trialing",
    active: "active",
    past_due: "past_due",
    canceled: "canceled",
    unpaid: "unpaid",
    incomplete: "incomplete",
    pause: "pause",
    ended: "ended"
  }

  ACCESS_GRANTING_STATUSES = %w[trialing active past_due]
  # validates :external_id, presence: true
  validates :rythm, inclusion: { in: %w[Annuel Mensuel] }
  scope :active_or_trialing, -> { where(status: ACCESS_GRANTING_STATUSES) }
  scope :recent, -> { order("current_period_end DESC NULLS LAST") }

  def active_or_trialing?
    ACCESS_GRANTING_STATUSES.include?(status)
  end

  TARIFS = {
    monthly: 5,
    annualy: [0, 50, 50, 49, 49, 48, 48, 47, 47, 46]
  }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def school_pricing
    @customer = StripeHelper.get_or_create_customer(current_user.school)
    authorize Subscription
  end

  def on_boarding
    redirect_to dashboard_path, notice: "Vous avez déjà un abonnement" if current_user.school.valid_subscription?

    authorize Subscription
    @sequence = 1
  end

  def new
    redirect_to dashboard_path, notice: "Vous avez déjà un abonnement" if current_user.school.valid_subscription?
    @sequence = 3
    @school = current_user.school
    @subscription = Subscription.new
    authorize @subscription
    # @customer = StripeHelper.get_or_create_customer(current_user)
  end

  def create
    @subcription = Subscription.new(subscription_params)
    @subcription.school = current_user.school
    authorize @subcription
    # @subcription.save
    # @subcription.update(params.require(:costs).permit(:trial_end, :current_period_start, :current_period_end))
    @customer = StripeHelper.get_or_create_customer(current_user.school)
    @session = Stripe::CheckoutsHelper.create_subscription_checkout(@customer, @subcription)
    redirect_to @session.url, allow_other_host: true
  end

  def cancel
  end

  def success
    authorize Subscription
    @sequence = 4
    #     Stripe.api_key = ENV["STRIPE_API_KEY"]
    # @subscription = Stripe::Subscription.retrieve( current_user.subscription.external_id)
  end
  def subscription_params
    params.require(:subscription).permit(:rythm, :quantity,:trial_end,:current_period_start,:current_period_end)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= turbo_frame_tag "sequence" do%>
	<h1 class='sub-title'>Abonnement pour <%=school.name.capitalize%></h1>
	<%= simple_form_for Subscription.new, html: { novalidate: false,
  data:{
  turbo: false,
  controller:'calculate-subscription',
  calculate_subscription_target:'form',
  calculate_subscription_tarifs_value:"#{raw Subscription::TARIFS.to_json}" }} do |f|%>
		<div class="sub-global-form">
			<div class='sub-form'>
				<div class="subscription-input">
					<p>Renouvellement</p>
					<p >Nb de classe</p>
				</div>
				<div class="subscription-input">
					<%= f.input :rythm, label:false,collection: ["Annuel","Mensuel"],selected:"Annuel", required: true,
            input_html:{data:{action:'change->calculate-subscription#calculate',calculate_subscription_target:'rythm' }} %>
					<%= f.input :quantity, label:false, collection: (1..15),selected: 1, required: true,
            input_html:{data:{action:'change->calculate-subscription#calculate',calculate_subscription_target:'quantity'}} %>
				</div>
			</div>
			<div class="vertical-bar"></div>
			<div class="sub-right-form">
				<div class="sub-input">
					<p>Fin période d'essai</p>
					<p>Coût Total</p>
					<p>Coût Mensuel (arrondi)</p>
					<p>Date de renouvellement</p>
				</div>
				<div class="subscription-input-right">
					<%= f.input_field :trial_end,readonly: true, class:'display-sub',html5: true, value: (Date.today + 25), label:false, required: true %>
					<%= f.input_field :total_cost,readonly: true, value: "50 €", class:'display-sub',
              data: {calculate_subscription_target:'totalCost'},
               label:false, required: true %>
					<%= f.input_field :montly_cost,readonly: true,value: "#{(50.0/12).round(3)} €", class:'display-sub',
              data: {calculate_subscription_target:'monthlyCost'},
               label:false, required: true %>
					<%= f.input_field :current_period_end,readonly: true, class:'display-sub',
              data: {calculate_subscription_target:'renewDate'},html5: true,
              value: (Date.today + 365 + 25), label:false, required: true %>
					<%= f.input_field :current_period_start,class: 'd-none',html5:true,  label:false, required: true, value: Date.today%>
				</div>
			</div>
		</div>
		<%= f.submit "Etape suivante", class: "create-school-code-btn"%>
	<% end %>
<% end %>

app/views/subscriptions/_stripe_cards.html.erb
<script async
  src="https://js.stripe.com/v3/buy-button.js"></script>
<div class="container backg-image-sub" data-controller='subscriptionnewtab'>
	<div class="speech w-50">
		<h3 class='p-2'>Bénéficiez de 25 jours d'essai, quelle que soit la durée de votre abonnement choisie.</h3>
	</div>
	<div class="stripe-card-select-subscription w-100" >
		<div class="stripe-card-select-subscription-cards w-100">
			<div class="left-card-sub_new">
				<div class="sub_header">
					<div class="period-sub-btn active left-sub-btn" data-subscriptionnewtab-target="tab1" data-action="click->subscriptionnewtab#displayAnnual">
						<h4>Annuel</h4>
						<p>50€ / an</p>
					</div>
					<div class="period-sub-btn right-sub-btn" data-subscriptionnewtab-target="tab2" data-action="click->subscriptionnewtab#displayMontlhy">
						<h4>Mensuel</h4>
						<p>5€/mois</p>
					</div>
					<div class="separator active" data-subscriptionnewtab-target="separator"></div>
				</div>
				<div class="subscription-detail">
					<h3><i class="fa-solid fa-check" style="color: #51d237;"></i>Inclus dés la période d'essai</h3>
					<p><i class="fa-solid fa-infinity"></i>Plans de travail illimités</p>
					<p><i class="fa-solid fa-infinity"></i>Ajout d'Exercice illimité</p>
					<p><i class="fa-solid fa-gears"></i>Génération Automatique de Plan de Travail</p>
					<p><i class="fa-solid fa-graduation-cap"></i>Evaluation Individuelle</p>
					<p><i class="fa-solid fa-people-roof"></i>Jusque deux classes par Professeur</p>
					<p><i class="fa-solid fa-chalkboard-user"></i>Un maximun de 40 élèves par Professeur</p>
				</div>
			</div>
			<stripe-buy-button
        buy-button-id="buy_btn_1NKhsRD36LSTpclfRo3a06ik"
        publishable-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"]%>"
        customer-email="<%= current_user.email %>"
        data-subscriptionnewtab-target="annualysub">
			</stripe-buy-button>
			<stripe-buy-button
        buy-button-id="buy_btn_1NKhxrD36LSTpclfpceKs7aW"
        publishable-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"]%>"
        customer-email="<%= current_user.email %>"
        class='d-none'
        data-subscriptionnewtab-target="monthlysub">
			</stripe-buy-button>
		</div>
		<%# <%= button_to "demarrer un abonnement annuel", subscriptions_path(type: "annualy"), data:{turbo:"false"} %>
		<%# <%= button_to "demarrer un abonnement mensuel", subscriptions_path(type: "monthly"), data:{turbo:"false"} %>
	</div>
</div>

app/views/subscriptions/cancel.html.erb
CANCEL

app/views/subscriptions/new.html.erb
<%= render 'shared/sequence_4', sequence: @sequence %>
<%= render 'form', school: @school %>

app/views/subscriptions/old_new.html.erb
<script async
  src="https://js.stripe.com/v3/buy-button.js"></script>
<div class="container backg-image-sub" data-controller='subscriptionnewtab'>
	<div class="speech w-50">
		<h3 class='p-2'>Bénéficiez de 25 jours d'essai, quelle que soit la durée de votre abonnement choisie.</h3>
	</div>
	<div class="stripe-card-select-subscription w-100" >
		<div class="stripe-card-select-subscription-cards w-100">
			<div class="left-card-sub_new">
				<div class="sub_header">
					<div class="period-sub-btn active left-sub-btn" data-subscriptionnewtab-target="tab1" data-action="click->subscriptionnewtab#displayAnnual">
						<h4>Annuel</h4>
						<p>50€ / an</p>
					</div>
					<div class="period-sub-btn right-sub-btn" data-subscriptionnewtab-target="tab2" data-action="click->subscriptionnewtab#displayMontlhy">
						<h4>Mensuel</h4>
						<p>5€/mois</p>
					</div>
					<div class="separator active" data-subscriptionnewtab-target="separator"></div>
				</div>
				<div class="subscription-detail">
					<h3><i class="fa-solid fa-check" style="color: #51d237;"></i>Inclus dés la période d'essai</h3>
					<p><i class="fa-solid fa-infinity"></i>Plans de travail illimités</p>
					<p><i class="fa-solid fa-infinity"></i>Ajout d'Exercice illimité</p>
					<p><i class="fa-solid fa-gears"></i>Génération Automatique de Plan de Travail</p>
          <p><i class="fa-solid fa-graduation-cap"></i>Evaluation Individuelle</p>
          <p><i class="fa-solid fa-people-roof"></i>Jusque deux classes par Professeur</p>
					<p><i class="fa-solid fa-chalkboard-user"></i>Un maximun de 40 élèves par Professeur</p>

        </div>
			</div>
			<stripe-buy-button
        buy-button-id="buy_btn_1NKhsRD36LSTpclfRo3a06ik"
        publishable-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"]%>"
        customer-email="<%= current_user.email %>"
        data-subscriptionnewtab-target="annualysub">
			</stripe-buy-button>
			<stripe-buy-button
        buy-button-id="buy_btn_1NKhxrD36LSTpclfpceKs7aW"
        publishable-key="<%= ENV["STRIPE_PUBLISHABLE_KEY"]%>"
        customer-email="<%= current_user.email %>"
        class='d-none'
        data-subscriptionnewtab-target="monthlysub">
			</stripe-buy-button>
		</div>
		<%# <%= button_to "demarrer un abonnement annuel", subscriptions_path(type: "annualy"), data:{turbo:"false"} %>
		<%# <%= button_to "demarrer un abonnement mensuel", subscriptions_path(type: "monthly"), data:{turbo:"false"} %>
	</div>
</div>

app/views/subscriptions/on_boarding.html.erb
<%= render 'shared/sequence_4', sequence: @sequence %>
<%= turbo_frame_tag "sequence" do %>
	<h1 class='sub-title'>Votre Abonnement</h1>
	<div class="sub-sequence-selection">
		<%= link_to join_school_path, data: { turbo_frame: "_top" } do%>
			<div class="action-school-box">Rejoindre une école</div>
		<% end %>
		<div class="vertical-bar"></div>
		<%= link_to  new_school_path, data: { turbo_frame: "_top" } do%>
			<div class="action-school-box">Créer votre groupe / école</div>
		<% end %>
	</div>
<% end %>

app/views/subscriptions/pricing.html.erb
<script async src="https://js.stripe.com/v3/pricing-table.js"></script>


<div class="container backg-image-sub" data-controller='subscriptionnewtab'>
	<div class="speech w-50">
		<h3 class='p-2'>Bénéficiez de 25 jours d'essai, quelle que soit la formule d'abonnement choisie.</h3>
	</div>
	<div class="stripe-card-select-subscription w-100" >
		<div class="stripe-card-select-subscription-cards w-100">
			<div class="left-card-sub_new">
				<div class="sub_header">
					<div class="period-sub-btn active" >
						<h4>Plan Annuel Ecole/Groupe</h4>
						<p>A partir de 100€ pour deux classes</p>
					</div>

				</div>
				<div class="subscription-detail">
					<h3><i class="fa-solid fa-check" style="color: #51d237;"></i>Inclus dés la période d'essai</h3>
					<p><i class="fa-solid fa-infinity"></i>Plans de travail illimités</p>
					<p><i class="fa-solid fa-infinity"></i>Ajout d'Exercice illimité</p>
					<p><i class="fa-solid fa-gears"></i>Génération Automatique de Plan de Travail</p>
          <p><i class="fa-solid fa-graduation-cap"></i>Evaluation Individuelle</p>
          <p><i class="fa-solid fa-people-roof"></i>Nb de professeurs non limité</p>
					<p><i class="fa-solid fa-chalkboard-user"></i>Une limite de 35 élèves par Classe</p>

        </div>
			</div>
			<stripe-pricing-table pricing-table-id="prctbl_1O0P6ND36LSTpclfX9OMEmmm"
customer-email= <%=@customer.email%>
publishable-key= <%=ENV["STRIPE_API_KEY"]%>
client-reference-id= <%= @customer.id %>
class='stripe-subscription-cards'  >
</stripe-pricing-table>
		</div>
		<%# <%= button_to "demarrer un abonnement annuel", subscriptions_path(type: "annualy"), data:{turbo:"false"} %>
		<%# <%= button_to "demarrer un abonnement mensuel", subscriptions_path(type: "monthly"), data:{turbo:"false"} %>
	</div>
</div>

app/views/subscriptions/school_pricing.html.erb
<script async src="https://js.stripe.com/v3/pricing-table.js"></script>


<div class="container backg-image-sub" data-controller='subscriptionnewtab'>
	<div class="speech w-50">
		<h3 class='p-2'>Bénéficiez de 25 jours d'essai, quelle que soit la formule d'abonnement choisie.</h3>
	</div>
	<div class="stripe-card-select-subscription w-100" >
		<div class="stripe-card-select-subscription-cards w-100">
			<div class="left-card-sub_new">
				<div class="sub_header">
					<div class="period-sub-btn active" >
						<h4>Plan Annuel Ecole/Groupe</h4>
						<p>A partir de 100€ pour deux classes</p>
					</div>

				</div>
				<div class="subscription-detail">
					<h3><i class="fa-solid fa-check" style="color: #51d237;"></i>Inclus dés la période d'essai</h3>
					<p><i class="fa-solid fa-infinity"></i>Plans de travail illimités</p>
					<p><i class="fa-solid fa-infinity"></i>Ajout d'Exercice illimité</p>
					<p><i class="fa-solid fa-gears"></i>Génération Automatique de Plan de Travail</p>
          <p><i class="fa-solid fa-graduation-cap"></i>Evaluation Individuelle</p>
          <p><i class="fa-solid fa-people-roof"></i>Nb de professeurs non limité</p>
					<p><i class="fa-solid fa-chalkboard-user"></i>Une limite de 35 élèves par Classe</p>

        </div>
			</div>
			<stripe-pricing-table pricing-table-id=<%=ENV["STRIPE_SCHOOL_PRICING_ID"]%>
customer-email= <%=@customer.email%>
publishable-key= <%=ENV["STRIPE_API_KEY"]%>
client-reference-id= <%= @customer.id %>
class='stripe-subscription-cards'  >
</stripe-pricing-table>
		</div>
		<%# <%= button_to "demarrer un abonnement annuel", subscriptions_path(type: "annualy"), data:{turbo:"false"} %>
		<%# <%= button_to "demarrer un abonnement mensuel", subscriptions_path(type: "monthly"), data:{turbo:"false"} %>
	</div>
</div>

app/views/subscriptions/success.html.erb
<%= render 'shared/sequence_4', sequence: @sequence %>
<div class="container-success">
	<h2>Confirmation d'abonnement</h2>
	<div class="success-icon">
		<i class="fa fa-check-circle"></i>
	</div>
	<p class="confirmation-message">Félicitations ! Votre abonnement a été validé et payé avec succès.</p>

</div>
<%= link_to  dashboard_path() do%>
	<i class="fa-solid fa-circle-arrow-left"></i>
Retour à votre Cartable
<% end %>